Fix: call reset and restore event triggers
adaptlearning/adapt-contrib-scoringAssessment pull request #5
Opened 2023-06-21 16:09 UTC by danielghost

Fixes #2.

### Fix
* Ensure all reset and restore events are triggered

### Dependency
 * https://github.com/adaptlearning/adapt-contrib-scoring/pull/9

2023-06-26 13:46 UTC, cahirodoherty-learningpool approved these changes
👀

2023-07-18 10:45 UTC, oliverfoster requested changes

2023-07-18 10:45 UTC, oliverfoster commented on js/AssessmentSet.js
> +   * @extends
Please revert these to override or remove them entirely

Extends is a synonym of augments, which is for `class Child extends Parent`
https://jsdoc.app/tags-augments.html

Override is for function overrides on the Child but isn't explicitly required.
https://jsdoc.app/tags-override.html

2023-07-18 10:56 UTC, oliverfoster commented
duplicate of #6

2023-07-18 10:56 UTC, closed without merging