Fix: amended "soft" reset condition (fixes #3).
adaptlearning/adapt-contrib-scoringAssessment pull request #6
Opened 2023-06-21 16:14 UTC by danielghost

Fixes #3.

### Fix
* Amended "soft" reset logic so all associated components have to be configured for a "soft" reset, to allow an assessment to remain complete following a reset.

2023-06-26 13:46 UTC, cahirodoherty-learningpool approved these changes
👀

2023-07-18 10:44 UTC, oliverfoster requested changes

2023-07-18 10:44 UTC, oliverfoster commented on js/AssessmentSet.js
> +   * @extends
Please revert these to override or remove them entirely

Extends is a synonym of augments, which is for `class Child extends Parent`
https://jsdoc.app/tags-augments.html

Override is for function overrides on the Child but isn't explicitly required.
https://jsdoc.app/tags-override.html

2023-07-18 10:44 UTC, oliverfoster commented on js/AssessmentSet.js
> +  get isSoftReset() {
What about where `this.presentationComponents.length === 0` or ¬this.questions.length === 0`?

```suggestion
    const hasNoQuestions = (this.questions.length === 0);
    const hasNoPresentationComponents = (this.presentationComponents.length === 0);
    const hasQuestionsSoftReset = (hasNoQuestions || this.resetConfig.questionsType === 'soft');
    const hasPresentationComponentsSoftReset = (hasNoPresentationComponents  || this.resetConfig.presentationComponentsType === 'soft');
    const hasSoftReset = (hasQuestionsSoftReset && hasPresentationComponentsSoftReset);
    return hasSoftReset;
```

2023-09-05 08:41 UTC, closed without merging